# Generated by Django 3.2.6 on 2022-07-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_helth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appointment',
            new_name='Appointmen',
        ),
    ]
