# Generated by Django 3.2.6 on 2022-07-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_helth', '0002_rename_appointment_appointmen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointmen',
            new_name='Appointment',
        ),
    ]
