# Generated by Django 4.0.6 on 2022-07-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_helth', '0005_auto_20220706_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_head', models.CharField(max_length=100)),
                ('main_heading', models.CharField(max_length=100)),
                ('banner_img', models.ImageField(upload_to='images/')),
                ('sub_text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
