# Generated by Django 4.0.6 on 2022-07-07 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_helth', '0007_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
