# Generated by Django 4.0.6 on 2022-07-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_helth', '0013_apponinment_alter_user_designation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='AppointmentBook',
        ),
        migrations.DeleteModel(
            name='Apponinment',
        ),
    ]
