# Generated by Django 4.0.6 on 2022-07-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_helth', '0014_rename_appointment_appointmentbook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbook',
            name='monday',
            field=models.BooleanField(default=False),
        ),
    ]
