# Generated by Django 4.0.6 on 2022-07-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_helth', '0015_appointmentbook_monday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentbook',
            name='monday',
        ),
    ]
