# Generated by Django 4.0.6 on 2022-07-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_helth', '0016_remove_appointmentbook_monday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbook',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
