# Generated by Django 4.0.6 on 2022-07-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_helth', '0017_alter_appointmentbook_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbook',
            name='monday',
            field=models.BooleanField(default=False),
        ),
    ]
